export default function  getData(){
    const fooddata = [
        {
            foodId:1,
            foodName:"冰淇淋",
            category:[
            {
              categoryId: 11,
              categoryName:"可爱多",
              image:"/src/assets/picture/可爱多.jpg",
              price:5,
              oldPrice:6,
              sellCount:90,
              daySellCount:6,
              weekSellCount:20,
              monthSellCount:30,
              kinds:[
                {
                kindsId: 111,
                categoryName:"草莓味",
                image:'/src/assets/可爱多/草莓味.jpg',
                price:5,
                count: 0,
              },
              {
                kindsId: 112,
                categoryName:"非常草莓味",
                image:'/src/assets/可爱多/非常草莓味.jpg',
                price:6,
                count: 0,
              },
              {
                kindsId: 113,
                categoryName:"非常曲奇奶风味",
                image:'/src/assets/可爱多/非常曲奇奶风味.jpg',
                price:6,
                count: 0,
              },
              {
                kindsId: 114,
                categoryName:"芒果酸奶味",
                image:'/src/assets/可爱多/芒果酸奶味.jpg',
                price:5,
                count: 0,
              },
              {
                kindsId: 115,
                categoryName:"巧克力味",
                image:'/src/assets/可爱多/巧克力味.jpg',
                price:5,
                count: 0,
              },
              {
                kindsId: 116,
                categoryName:"香芋牛奶味",
                image:'/src/assets/可爱多/香芋牛奶味.jpg',
                price:5,
                count: 0,
                },
              ],
           },
           {
            categoryId: 12,
            categoryName:"哈根达斯",
            price:10,
            sellCount:63,
            daySellCount:2,
            weekSellCount:7,
            monthSellCount:20,
            image:"/src/assets/冰淇淋/哈根达斯/曲奇香奶口味.jpg",
            kinds:[
              {
                kindsId: 121,
                categoryName:"曲奇香奶口味",
                image:'/src/assets/冰淇淋/哈根达斯/曲奇香奶口味.jpg',
                price:10,
                count: 0,
              },
              {
                kindsId: 122,
                categoryName:"夏威夷果仁口味",
                image:'/src/assets/冰淇淋/哈根达斯/夏威夷果仁口味.jpg',
                price:10,
                count: 0,
              }
            ]
           },
           {
            categoryId: 13,
            categoryName:"巧乐兹",
            price:4,
            oldPrice:6,
            sellCount:125,
            daySellCount:10,
            weekSellCount:36,
            monthSellCount:52,
            image:"/src/assets/冰淇淋/巧乐兹/蛋奶双层巧克力味.jpg",
            kinds:[
              {
                kindsId: 131,
                categoryName:"蛋奶双层巧克力味",
                image:'/src/assets/冰淇淋/巧乐兹/蛋奶双层巧克力味.jpg',
                price:4,
                count: 0,
              },
              {
                kindsId: 132,
                categoryName:"柑橘口味",
                image:'/src/assets/冰淇淋/巧乐兹/柑橘口味.jpg',
                price:4,
                count: 0,
              },
              {
                kindsId: 133,
                categoryName:"经典巧恋果口味",
                image:'/src/assets/冰淇淋/巧乐兹/经典巧恋果口味.jpg',
                price:4,
                count: 0,
              },
              {
                kindsId: 134,
                categoryName:"经典巧丝绒口味",
                image:'/src/assets/冰淇淋/巧乐兹/经典巧丝绒口味.jpg',
                price:4,
                count: 0,
              }
            ]
           },
           {
            categoryId: 14,
            categoryName:"甄稀",
            price:6,
            sellCount:96,
            daySellCount:4,
            weekSellCount:10,
            monthSellCount:24,
            image:"/src/assets/冰淇淋/甄稀/轻恬香草口味.jpg",
            kinds:[
              {
                kindsId: 141,
                categoryName:"轻恬香草口味",
                image:'/src/assets/冰淇淋/甄稀/轻恬香草口味.jpg',
                price:6,
                count: 0,
              },
              {
                kindsId: 142,
                categoryName:"热恋草莓口味",
                image:'/src/assets/冰淇淋/甄稀/热恋草莓口味.jpg',
                price:6,
                count: 0,
              },
              {
                kindsId: 143,
                categoryName:"提拉米苏口味",
                image:'/src/assets/冰淇淋/甄稀/提拉米苏口味.jpg',
                price:6,
                count: 0,
              },
              {
                kindsId: 144,
                categoryName:"希腊风味酸奶口味",
                image:'/src/assets/冰淇淋/甄稀/希腊风味酸奶口味.jpg',
                price:6,
                count: 0,
              }
            ]
           },
           {
            categoryId: 15,
            categoryName:"钟薛高",
            sellCount:102,
            daySellCount:8,
            weekSellCount:15,
            monthSellCount:34,
            image:"/src/assets/冰淇淋/钟薛高/丝绒可可口味.jpg",
            price:20,
            oldPrice:25,
            kinds:[
              {
                kindsId: 151,
                categoryName:"丝绒可可口味",
                image:'/src/assets/冰淇淋/钟薛高/丝绒可可口味.jpg',
                price:20,
                count: 0,
              },
              {
                kindsId: 152,
                categoryName:"半巧主义口味",
                image:'/src/assets/冰淇淋/钟薛高/半巧主义口味.jpg',
                price:20,
                count: 0,
              },
              {
                kindsId: 153,
                categoryName:"芝士草莓口味",
                image:'/src/assets/冰淇淋/钟薛高/芝士草莓口味.png',
                price:20,
                count: 0,
              },
            ]
           },
           {
            categoryId: 16,
            categoryName:"可爱多",
            sellCount:234,
            daySellCount:12,
            weekSellCount:35,
            monthSellCount:62,
            image:"/src/assets/可爱多/草莓味.jpg",
            price:4,
            oldPrice:5,
            kinds:[
              {
                kindsId: 161,
                categoryName:"草莓口味",
                image:'/src/assets/可爱多/草莓味.jpg',
                price:4,
                count: 0,
              },
              {
                kindsId: 162,
                categoryName:"非常草莓口味",
                image:'/src/assets/可爱多/非常草莓味.jpg',
                price:4,
                count: 0,
              },
              {
                kindsId: 163,
                categoryName:"非常曲奇奶风口味",
                image:'/src/assets/可爱多/非常曲奇奶风味.jpg',
                price:4,
                count: 0,
              },
              {
                kindsId: 164,
                categoryName:"芒果酸奶口味",
                image:'/src/assets/可爱多/芒果酸奶味.jpg',
                price:4,
                count: 0,
              },
              {
                kindsId: 165,
                categoryName:"巧克力口味",
                image:'/src/assets/可爱多/巧克力味.jpg',
                price:4,
                count: 0,
              },
              {
                kindsId: 166,
                categoryName:"香芋牛奶口味",
                image:'/src/assets/可爱多/香芋牛奶味.jpg',
                price:4,
                count: 0,
              },
            ]
           },
          ]
        },

          {
          foodId:2,
          foodName:"溜溜梅",
          category:[
          {
            categoryId: 21,
            categoryName:"九制梅",
            image:"/src/assets/picture/溜溜梅.jpg",
            price:5,
            oldPrice:6,
            sellCount:90,
            daySellCount:7,
            weekSellCount:15,
            monthSellCount:45,
            count: 0,
          },
          {
            categoryId: 22,
            categoryName:"清梅",
            image:'/src/assets/溜溜梅/清梅.jpg',
            price:5,
            sellCount: 20,
            daySellCount:2,
            weekSellCount:4,
            monthSellCount:8,
            count: 0,
          },
          {
            categoryId: 23,
            categoryName:"乌梅",
            image:'/src/assets/溜溜梅/乌梅.jpg',
            price:5,
            sellCount: 22,
            daySellCount:3,
            weekSellCount:6,
            monthSellCount:9,
            count: 0,
          },
          {
            categoryId: 24,
            categoryName:"雪梅",
            image:'/src/assets/溜溜梅/雪梅.jpg',
            price:5,
            sellCount: 70,
            daySellCount:4,
            weekSellCount:7,
            monthSellCount:9,
            count: 0,
          },
          {
            categoryId: 25,
            categoryName:"咖啡梅",
            image:'/src/assets/溜溜梅/咖啡梅.jpg',
            price:5,
            oldPrice:6,
            sellCount: 50,
            daySellCount:2,
            weekSellCount:4,
            monthSellCount:8,
            count: 0,
          },
          {
            categoryId: 26,
            categoryName:"话梅",
            image:'/src/assets/溜溜梅/话梅.jpg',
            price:5,
            oldPrice:6,
            sellCount: 50,
            daySellCount:3,
            weekSellCount:9,
            monthSellCount:12,
            count: 0,
          },
          {
            categoryId: 27,
            categoryName:"情人梅",
            image:'/src/assets/溜溜梅/情人梅.jpg',
            price:5,
            oldPrice:6,
            sellCount: 20,
            daySellCount:2,
            weekSellCount:4,
            monthSellCount:6,
            count: 0,
          },
          {
            categoryId: 28,
            categoryName:"凤梨梅",
            image:'/src/assets/溜溜梅/凤梨梅.jpg',
            price:5,
            oldPrice:6,
            sellCount: 60,
            daySellCount:8,
            weekSellCount:14,
            monthSellCount:26,
            count: 0,
          },
          {
            categoryId: 29,
            categoryName:"绿茶梅",
            image:'/src/assets/溜溜梅/绿茶梅.jpg',
            price:5,
            oldPrice:6,
            sellCount: 10,
            daySellCount:1,
            weekSellCount:3,
            monthSellCount:5,
            count: 0,
          }
        ]
       },
       {
        foodId:3,
        foodName:"奥利奥",
        category:[
          {
            categoryId: 31,
            categoryName:"奥利奥",
            image:'/src/assets/奥利奥/草莓味夹心.jpg',
            price:4,
            oldPrice:5,
            sellCount: 520,
            daySellCount:25,
            weekSellCount:40,
            monthSellCount:73,
            kinds:[
              {
                kindsId: 311,
                categoryName:"草莓味夹心",
                image:'/src/assets/奥利奥/草莓味夹心.jpg',
                price:4,
                count: 0,
              },
              {
                kindsId: 332,
                categoryName:"红丝绒缤纷豆味",
                image:'/src/assets/奥利奥/红丝绒缤纷豆味.jpg',
                price:4,
                count: 0,
              },
              {
                kindsId: 333,
                categoryName:"巧克力夹心原味",
                image:'/src/assets/奥利奥/巧克力夹心原味.jpg',
                price:4,
                count: 0,
              },
              {
                kindsId: 334,
                categoryName:"轻甜夹心",
                image:'/src/assets/奥利奥/轻甜夹心.png',
                price:4,
                count: 0,
              },
              {
                kindsId: 335,
                categoryName:"树莓味+蓝莓味",
                image:'/src/assets/奥利奥/树莓味+蓝莓味.jpg',
                price:4,
                count: 0,
              },
            ]
          }
        ]
       },

       {
        foodId:4,
        foodName:"麻辣王子",
        category:[
        {
          categoryId: 41,
          categoryName:"单包麻辣王子",
          image:"/src/assets/picture/麻辣王子.jpg",
          price:1,
          oldPrice:1.5,
          sellCount:490,
          daySellCount:52,
          weekSellCount:92,
          monthSellCount:104,
          count: 0,
        },
        {
          categoryId: 42,
          categoryName:"单袋麻辣王子",
          image:'/src/assets/麻辣王子/单袋麻辣王子.png',
          price:5,
          oldPrice:7,
          sellCount: 300,
          daySellCount:34,
          weekSellCount:64,
          monthSellCount:92,
          count: 0,
        },
        {
          categoryId: 43,
          categoryName:"麻辣王子大礼包",
          image:'/src/assets/麻辣王子/麻辣王子大礼包.jpg',
          price:10,
          oldPrice:12,
          sellCount: 300,
          daySellCount:26,
          weekSellCount:55,
          monthSellCount:87,
          count: 0,
        },
        {
          categoryId: 44,
          categoryName:"单箱麻辣王子",
          image:'/src/assets/麻辣王子/单箱麻辣王子.jpg',
          price:20,
          oldPrice:25,
          sellCount: 400,
          daySellCount:39,
          weekSellCount:65,
          monthSellCount:93,
          count: 0,
        },
        ]
      }  
    ]
    return fooddata
}
